# Generated by Django 4.2.4 on 2023-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_video_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='photos',
            field=models.TextField(default='NULL', max_length=1000),
        ),
    ]
